---
# ──────────────────────────────────────────────────────────
# Ghost host-specific vars
# ──────────────────────────────────────────────────────────

ansible_host: 100.125.8.125
ansible_user: root

grist_port: 8484
dockhand_port: 3000
